### ISSUE TITLE
How to render movie clips?

### ISSUE THREAD

**Issue by Draggie306** [Vorono4ka/XCoder#3]
After hours of reading and editing hundreds of lines of code to no avail, I found this repo which is definitely the most useful. However, I can’t seem to get it to create the movie scripts? What do I need to invoke when running it, if anything? I’m looking specifically at `background_brawentines `and `background_darkmas`.

(sorry for the demands, I’m tired and haven’t got round to looking through all the scripts yet!)

**Comment by Vorono4ka** [comment]
Hello! In look into [this file](https://github.com/Vorono4ka/XCoder/blob/master/system/lib/features/cut_sprites.py). There are some commented lines for movie clips rendering
